version: '3'
# Section for defining your containers
services:
  database:
    # The prebuilt container we want to use
    image: 'postgres:latest'
    # connects the container to the outside world
    ports:
      - "5432:5432"
    # tell the container during setup how to configure
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    # this appears to be the credential information of our database
    volumes:
      - ./data:/var/lib/postgresql/data
